name: csv_armor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  json_schema: ^5.1.7
  yaml: ^3.1.2
  json_annotation: ^4.9.0
  embed_annotation: ^1.2.1
  collection: ^1.18.0
  path: ^1.9.0
  yaml_edit: ^2.2.1
  copy_with_extension: ^5.0.4
  quiver: ^3.2.1
  dart_mappable: ^4.2.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  embed: ^1.3.1
  lint: ^2.3.0
  copy_with_extension_gen: ^5.0.4
  dart_mappable_builder: ^4.2.3
