name: csv_armor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  json_schema: ^5.1.7
  yaml: ^3.1.2
  json_annotation: ^4.9.0



dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
