"$schema": "https://json-schema.org/draft/07/schema"
"title": "CSV Encoder Config"

type: object
properties:
  field_separator:
    type: string
    default: ","
  record_separator:
    type: string
    enum: [ "CRLF", "LF", "CR" ]
  terminates_with_record_separator:
    type: boolean
    default: false
  field_quote:
    oneOf:
      - type: object
        properties:
          quote:
            type: string
            default: '"'
          escape:
            type: string
            default: '""'
          always:
            type: boolean
            default: false
        additionalProperties: false
      - type: object
        properties:
          left_quote:
            type: string
          left_escape:
            type: string
          right_quote:
            type: string
          right_escape:
            type: string
          always:
            type: boolean
            default: false
        additionalProperties: false
additionalProperties: false
